services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: elazazy
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    expose:
      - "5432"
    restart: unless-stopped

  web:
    container_name: elazazy-api
    image: elazazymohamed/elazazy-api
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activate the docker profile
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
#      SPRING_DATASOURCE_USERNAME: elazazy
#      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db
    restart: unless-stopped

  elazazy-react:
    container_name: elazazy-react
    image: elazazymohamed/elazazy-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8080  # Pass the build argument
    ports:
      - "3000:5173"
    depends_on:
      - web
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
