server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: local

  flyway:
    schemas: public
    driver-class-name: org.postgresql.Driver

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet # This is the default value, so you can skip spring configuration
